package db

import "go.mongodb.org/mongo-driver/x/mongo/driver/uuid"

type CombinValue struct {
	// ID generated by mongo
	ID uuid.UUID `bson:"_id"`
	// Number of players in combin
	Size int `bson:"size"`
	// Players part of a combination we store the value for
	Players []string `bson:"players"`
	// Cumulated time played together for this combination
	Minutes int `bson:"minutes,omitempty"`
	// Cumulated score for when this combination played together
	CumulatedScore float64 `bson:"cumulated_score,omitempty"`
	// Averaged score per 90 minutes for this combination
	Score float64 `bson:"score,omitempty"`
	// Number of combinations a player as been part of
	CombinCount int `bson:"combin_count,omitempty"` // Only if len(Players) = 1
	// Actual Shapley Value of a player
	// It is actually only an estimation as not all the combinations are counted
	ShapleyValue float64 `bson:"shapley_value,omitempty"` // Only if len(Players) = 1
}
